#!/usr/bin/env python3
import argparse
import math
import os
from pathlib import Path


def parse_mtl(path):
    colors = {}
    current = None
    if not path.exists():
        return colors
    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if parts[0] == "newmtl" and len(parts) >= 2:
            current = parts[1]
        elif parts[0] == "Kd" and current and len(parts) >= 4:
            colors[current] = tuple(max(0.0, min(1.0, float(v))) for v in parts[1:4])
    return colors


def parse_index(token, count):
    if not token:
        return None
    idx = int(token)
    if idx < 0:
        return count + idx
    return idx - 1


def normalize(v):
    mag = math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2])
    if mag <= 0.000001:
        return (0.0, 1.0, 0.0)
    return (v[0] / mag, v[1] / mag, v[2] / mag)


def sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def cross(a, b):
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def shade_color(kd, normal):
    light = normalize((-0.45, 0.8, 0.38))
    n = normalize(normal)
    lambert = max(0.0, n[0] * light[0] + n[1] * light[1] + n[2] * light[2])
    shade = 0.54 + 0.46 * lambert
    return tuple(int(max(0, min(255, round(c * shade * 255.0)))) for c in kd)


def parse_obj(path):
    positions = []
    normals = []
    vertices = []
    mtl_colors = {}
    current_color = (0.85, 0.86, 0.9)
    src_dir = path.parent

    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        kind = parts[0]
        if kind == "mtllib" and len(parts) >= 2:
            mtl_colors.update(parse_mtl(src_dir / " ".join(parts[1:])))
        elif kind == "v" and len(parts) >= 4:
            positions.append((float(parts[1]), float(parts[2]), float(parts[3])))
        elif kind == "vn" and len(parts) >= 4:
            normals.append(normalize((float(parts[1]), float(parts[2]), float(parts[3]))))
        elif kind == "usemtl" and len(parts) >= 2:
            current_color = mtl_colors.get(parts[1], current_color)
        elif kind == "f" and len(parts) >= 4:
            refs = []
            for token in parts[1:]:
                fields = token.split("/")
                vi = parse_index(fields[0], len(positions))
                ni = parse_index(fields[2], len(normals)) if len(fields) >= 3 else None
                if vi is None or vi < 0 or vi >= len(positions):
                    raise ValueError(f"bad vertex index in {path}: {token}")
                refs.append((vi, ni))
            for i in range(1, len(refs) - 1):
                tri = [refs[0], refs[i], refs[i + 1]]
                p0 = positions[tri[0][0]]
                p1 = positions[tri[1][0]]
                p2 = positions[tri[2][0]]
                face_normal = normalize(cross(sub(p1, p0), sub(p2, p0)))
                for vi, ni in tri:
                    p = positions[vi]
                    n = normals[ni] if ni is not None and 0 <= ni < len(normals) else face_normal
                    r, g, b = shade_color(current_color, n)
                    vertices.append((p[0], p[1], p[2], r, g, b, 255))
    if not vertices:
        raise ValueError(f"no triangles in {path}")
    radius = 0.0
    height = 0.0
    for x, y, z, *_ in vertices:
        radius = max(radius, math.sqrt(x * x + z * z))
        height = max(height, y)
    return vertices, radius, height


def c_ident(name):
    out = []
    for ch in name:
        out.append(ch.upper() if ch.isalnum() else "_")
    return "".join(out)


def write_outputs(meshes, out_h, out_c):
    guard = "TRAD_GENERATED_ASSETS_H"
    h = []
    h.append("/* Generated by tools/obj_to_c.py. Do not edit by hand. */\n")
    h.append(f"#ifndef {guard}\n#define {guard}\n\n")
    h.append("#include <stdint.h>\n\n")
    h.append("typedef struct TradVertex {\n")
    h.append("    float x, y, z;\n")
    h.append("    uint8_t r, g, b, a;\n")
    h.append("} TradVertex;\n\n")
    h.append("typedef struct TradMesh {\n")
    h.append("    const TradVertex *vertices;\n")
    h.append("    int vertex_count;\n")
    h.append("    float radius;\n")
    h.append("    float height;\n")
    h.append("} TradMesh;\n\n")
    h.append("typedef enum TradMeshId {\n")
    for i, mesh in enumerate(meshes):
        comma = "," if i + 1 < len(meshes) else ""
        h.append(f"    TRAD_MESH_{c_ident(mesh['name'])} = {i}{comma}\n")
    h.append("} TradMeshId;\n\n")
    h.append(f"#define TRAD_MESH_COUNT {len(meshes)}\n")
    h.append("extern const TradMesh trad_meshes[TRAD_MESH_COUNT];\n\n")
    h.append(f"#endif /* {guard} */\n")

    c = []
    c.append("/* Generated by tools/obj_to_c.py. Do not edit by hand. */\n")
    c.append('#include "generated_assets.h"\n\n')
    for mesh in meshes:
        ident = c_ident(mesh["name"]).lower()
        c.append(f"static const TradVertex trad_vertices_{ident}[] = {{\n")
        for x, y, z, r, g, b, a in mesh["vertices"]:
            c.append(f"    {{ {x:.6f}f, {y:.6f}f, {z:.6f}f, {r}, {g}, {b}, {a} }},\n")
        c.append("};\n\n")
    c.append("const TradMesh trad_meshes[TRAD_MESH_COUNT] = {\n")
    for mesh in meshes:
        ident = c_ident(mesh["name"]).lower()
        count = len(mesh["vertices"])
        c.append(
            f"    [TRAD_MESH_{c_ident(mesh['name'])}] = "
            f"{{ trad_vertices_{ident}, {count}, {mesh['radius']:.6f}f, {mesh['height']:.6f}f }},\n"
        )
    c.append("};\n")

    out_h.write_text("".join(h), encoding="utf-8")
    out_c.write_text("".join(c), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--src-dir", required=True)
    parser.add_argument("--out-h", required=True)
    parser.add_argument("--out-c", required=True)
    parser.add_argument("models", nargs="+")
    args = parser.parse_args()

    src_dir = Path(args.src_dir)
    meshes = []
    for name in args.models:
        obj = src_dir / f"{name}.obj"
        vertices, radius, height = parse_obj(obj)
        meshes.append({"name": name, "vertices": vertices, "radius": radius, "height": height})

    out_h = Path(args.out_h)
    out_c = Path(args.out_c)
    out_h.parent.mkdir(parents=True, exist_ok=True)
    out_c.parent.mkdir(parents=True, exist_ok=True)
    write_outputs(meshes, out_h, out_c)


if __name__ == "__main__":
    main()
