/* Generated by tools/obj_to_c.py. Do not edit by hand. */
#ifndef TRAD_GENERATED_ASSETS_H
#define TRAD_GENERATED_ASSETS_H

#include <stdint.h>

typedef struct TradVertex {
    float x, y, z;
    uint8_t r, g, b, a;
} TradVertex;

typedef struct TradMesh {
    const TradVertex *vertices;
    int vertex_count;
    float radius;
    float height;
} TradMesh;

typedef enum TradMeshId {
    TRAD_MESH_CRAFT_RACER = 0,
    TRAD_MESH_CRAFT_SPEEDERA = 1,
    TRAD_MESH_CRAFT_SPEEDERB = 2,
    TRAD_MESH_CRAFT_SPEEDERC = 3,
    TRAD_MESH_CRAFT_SPEEDERD = 4,
    TRAD_MESH_CRAFT_CARGOA = 5,
    TRAD_MESH_CRAFT_CARGOB = 6,
    TRAD_MESH_CRAFT_MINER = 7,
    TRAD_MESH_METEOR_DETAILED = 8,
    TRAD_MESH_METEOR = 9,
    TRAD_MESH_METEOR_HALF = 10,
    TRAD_MESH_ROCK_LARGEA = 11,
    TRAD_MESH_ROCKS_SMALLA = 12,
    TRAD_MESH_CRATERLARGE = 13,
    TRAD_MESH_TERRAIN_ROADSTRAIGHT = 14,
    TRAD_MESH_TERRAIN_ROADCORNER = 15,
    TRAD_MESH_TERRAIN_ROADCROSS = 16,
    TRAD_MESH_PLATFORM_LONG = 17,
    TRAD_MESH_PLATFORM_LARGE = 18,
    TRAD_MESH_TURRET_SINGLE = 19,
    TRAD_MESH_SATELLITEDISH_DETAILED = 20,
    TRAD_MESH_HANGAR_SMALLA = 21,
    TRAD_MESH_GATE_COMPLEX = 22,
    TRAD_MESH_MACHINE_GENERATORLARGE = 23
} TradMeshId;

#define TRAD_MESH_COUNT 24
extern const TradMesh trad_meshes[TRAD_MESH_COUNT];

#endif /* TRAD_GENERATED_ASSETS_H */
