/* Generated by tools/obj_to_c.py. Do not edit by hand. */
#ifndef TRAD_GENERATED_ASSETS_H
#define TRAD_GENERATED_ASSETS_H

#include <stdint.h>

typedef struct TradVertex {
    float x, y, z;
    uint8_t r, g, b, a;
} TradVertex;

typedef struct TradMesh {
    const TradVertex *vertices;
    int vertex_count;
    float radius;
    float height;
} TradMesh;

typedef enum TradMeshId {
    TRAD_MESH_CRAFT_RACER = 0,
    TRAD_MESH_CRAFT_SPEEDERA = 1,
    TRAD_MESH_CRAFT_SPEEDERB = 2,
    TRAD_MESH_CRAFT_CARGOA = 3,
    TRAD_MESH_METEOR_DETAILED = 4
} TradMeshId;

#define TRAD_MESH_COUNT 5
extern const TradMesh trad_meshes[TRAD_MESH_COUNT];

#endif /* TRAD_GENERATED_ASSETS_H */
